jobs: 25
cluster: "sbatch --time={resources.time_min} --mem={resources.mem_mb} -c {resources.cpus} -o slurm/logs/{rule}_{wildcards} -e slurm/logs/{rule}_{wildcards} --mail-type=ALL --mail-user=akiledal@udel.edu"
use-conda: true
conda-frontend: mamba
default-resources: [cpus=4, mem_mb=16000, time_min=120]
resources: [cpus=102, mem_mb=1000000]
latency-wait: 10
